make: TEST.c bruteForce.c rabinKarp.c boyerMoore.c
	gcc TEST.c bruteForce.c rabinKarp.c boyerMoore.c tools.c -o test

edit:
	vim TEST.c bruteForce.c rabinKarp.c boyerMoore.c tools.c main.h

run:
	./test

