make: TEST.c prim.c kruskal.c tools.c
	gcc TEST.c prim.c kruskal.c tools.c -o test

edit:
	vim TEST.c prim.c kruskal.c tools.c main.h

clean:
	rm test

run1:
	./test < Graphs/graph01.txt

run2:
	./test < Graphs/graph02.txt
	
run3:
	./test < Graphs/graph03.txt

