make: TEST.c naivePebbles.c memoizedPebbles.c tabularPebbles.c tools.c
	gcc TEST.c naivePebbles.c memoizedPebbles.c tabularPebbles.c tools.c -o test

edit:
	vim TEST.c naivePebbles.c memoizedPebbles.c tabularPebbles.c main.h

run:
	./test

