make: TEST.c naiveLeastChange.c memoizedLeastChange.c tabularLeastChange.c tools.c
	gcc TEST.c naiveLeastChange.c memoizedLeastChange.c tabularLeastChange.c tools.c -o test

edit:
	vim TEST.c naiveLeastChange.c memoizedLeastChange.c tabularLeastChange.c tools.c main.h

run:
	./test

