make: TEST.c selectionSort.c mergeSort.c quickSort.c tools.c
	gcc TEST.c selectionSort.c mergeSort.c quickSort.c tools.c -o test

edit:
	vim TEST.c selectionSort.c mergeSort.c quickSort.c heapSort.c tools.c main.h

run:
	./test

