make: TEST.c naiveFibonacci.c memoizedFibonacci.c tabularFibonacci.c tools.c
	gcc TEST.c naiveFibonacci.c memoizedFibonacci.c tabularFibonacci.c tools.c -o test

edit:
	vim TEST.c naiveFibonacci.c memoizedFibonacci.c tabularFibonacci.c tools.c main.h

run:
	./test

