make: TEST.c naiveNchooseK.c memoizedNchooseK.c tabularNchooseK.c tools.c
	gcc TEST.c naiveNchooseK.c memoizedNchooseK.c tabularNchooseK.c tools.c -o test

edit:
	vim TEST.c naiveNchooseK.c memoizedNchooseK.c tabularNchooseK.c main.h

run:
	./test

